"""player add espn id

Revision ID: 134669846d6a
Revises: f48ec3dc9614
Create Date: 2021-07-02 21:50:04.377941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134669846d6a'
down_revision = 'f48ec3dc9614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'player', 
        sa.Column('espn_id', sa.Integer(), nullable=False, server_default='-1')
)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'espn_id')
    # ### end Alembic commands ###
