"""player non-nullable name

Revision ID: 883b87405297
Revises: 134669846d6a
Create Date: 2021-07-04 22:58:45.706266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883b87405297'
down_revision = '134669846d6a'
branch_labels = None
depends_on = None

### https://alembic.sqlalchemy.org/en/latest/batch.html

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player") as batch_op:
        batch_op.alter_column('name', nullable=False, server_default="")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player") as batch_op:
        batch_op.alter_column('name', nullable=True, server_default="NULL")
    # ### end Alembic commands ###
